### ISSUE TITLE
Cannot get `cisco.ise.active_directory_groups_by_domain_info` to work

### ISSUE THREAD

**Issue by israelfdzhdz** [CiscoISE/ansible-ise#100]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest ISE Collection version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
`cisco.ise.active_directory_groups_by_domain_info` module is not working. When running the following playbook:
```yaml
---
- name: Get Active Directory Group Information
  hosts: ise
  gather_facts: no
  tasks:
    - name: Get Active Directory Group By Name
      cisco.ise.active_directory_groups_by_domain_info:
        ise_hostname: example.ise.org
        ise_username: admin
        ise_password: Examp1ePassw0rd!*
        ise_verify: false
        id: 37109d50-5814-11ee-9f78-f2b245013e94
        additionalData:
          - name: domain
             value: ise.org
          - name: filter
             value: Backup Operators
        ise_debug: true
        ise_single_request_timeout: 300
```
Ansible returns the below error:
```
TASK [Get all Active Directory Groups By Domain] **************************************************************************************************************************************************************************
task path: /home/isrferna/ansible/regular_tasks/ad_add_group.yml:17
Friday 22 September 2023  02:54:34 +0000 (0:00:00.431)       0:00:00.431 ****** 
The full traceback is:
Traceback (most recent call last):
  File "/home/isrferna/venv/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 165, in run
    res = self._execute()
  File "/home/isrferna/venv/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 677, in _execute
    result["_ansible_no_log"] = no_log
TypeError: 'NoneType' object does not support item assignment
fatal: [localhost]: FAILED! => 
  msg: 'Unexpected failure during module execution: ''NoneType'' object does not support item assignment'
  stdout: ''

PLAY RECAP ****************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Expected behavior**
It is expected to get the group information that corresponds to the provided name within the specified domain.

**Screenshots**
Using `ansible.builtin.uri` module:
```yaml
- name: Get Active Directory Group By Name
      ansible.builtin.uri:
        url: https://example.ise.org/ers/config/activedirectory/37109d50-5814-11ee-9f78-f2b245013e94/getGroupsByDomain
        method: PUT
        body_format: json
        user: admin
        password: Examp1ePassw0rd!*
        status_code: 200
        return_content: true
        headers:
          Content-Type: application/json
          Accept: application/json
        body:
          OperationAdditionalData:
            additionalData:
              - name: domain
                value: ise.org
              - name: filter
                value: Backup Operators
        validate_certs: false
        timeout: 300
```
it is returning:
```
ok: [localhost] => changed=false 
  cache_control: no-cache, no-store, must-revalidate
  connection: close
  content: |-
    {
      "ERSActiveDirectoryGroups" : {
        "groups" : [ {
          "name" : "ise.org/Builtin/Backup Operators",
          "sid" : "ise.org/S-1-5-12-551",
          "type" : "BUILTIN, DOMAIN LOCAL"
        } ]
      }
    }
```
**Environment (please complete the following information):**
* ISE version and patch: 3.2 Patch 1
* Ansible version: 2.15.2
* ISE collection version: 2.5.15
* OS version: Ubuntu 20.04.6 LTS

**Comment by DbarrantesE** [comment]
Hi @israelfdzhdz,  according to the debug report, the issue has been resolved. You can try testing it to verify that everything is working correctly, or if we need to make any further adjustments to our code.
