### ISSUE TITLE
`cisco.ise.support_bundle_download` keeps failing after downloading the file

### ISSUE THREAD

**Issue by temoromac** [CiscoISE/ansible-ise#139]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest ISE Collection version?
* [X] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Name of the module**
`cisco.ise.support_bundle_download`

**Describe the bug**
After downloading the support bundle, the module fails with the following error:

**Expected behavior**
After downloading the support bundle, task should not fail.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

![image](https://github.com/user-attachments/assets/f4c334c3-8496-4fb9-8c5a-c3abcfbd9722)

**Debug**
Enable debugging and add CiscoISE output request and reponse.
* exporting `export ISE_DEBUG=True`
* playbook `ise_debug: True`

```
TASK [Download support bundle] ***********************************************************************************************************************************************************************************
task path: /Users/arterome/Documents/github/ise-cube/download_support_bundle.yml:6
Attempt 1

Request
        URL: https://ise.domain.com/ers/config/supportbundledownload
        Method: PUT
        Headers: 
                User-Agent: python-cisco-ise/3.3_patch_1
                Accept-Encoding: gzip, deflate
                Accept: application/json
                Connection: keep-alive
                authorization: Basic XXXXXXX
                Content-type: application/json;charset=utf-8
        Params:
              {}
        Body:
            {
                "ErsSupportBundleDownload": {
                    "fileName": "ise-support-bundle-pk-ise-admin-08-08-2024-23-05.tar.gpg"
                }
            }
        Stream:
                True

Response
        Status: 200 - 
        Headers: 
                Content-Type: application/octet-stream
                Transfer-Encoding: chunked
                Connection: keep-alive
                Cache-Control: no-cache, no-store, must-revalidate
                Set-Cookie: JSESSIONIDSSO=81F52FF532D1B725E9272021C5E84419; Path=/; Secure; HttpOnly, APPSESSIONID=426416DFC59729AB5651583DF4E18C43; Path=/ers; Secure; HttpOnly
                Pragma: no-cache
                Expires: Thu, 01 Jan 1970 00:00:00 GMT
                X-Frame-Options: SAMEORIGIN
                Strict-Transport-Security: max-age=31536000; includeSubDomains
                X-Content-Type-Options: nosniff
                X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-XSS-Protection: 1; mode=block
                Content-Disposition: attachment; filename="supportbundledownload.tar.gpg"
                Date: Wed, 14 Aug 2024 14:09:08 GMT
                Server: 
Downloading ./ise-support-bundle-pk-ise-admin-08-08-2024-23-05.tar.gpg
Downloaded ./ise-support-bundle-pk-ise-admin-08-08-2024-23-05.tar.gpg
The full traceback is:
Traceback (most recent call last):
  File "/Users/arterome/Documents/github/ise-cube/venv/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 164, in run
    res = self._execute()
          ^^^^^^^^^^^^^^^
  File "/Users/arterome/Documents/github/ise-cube/venv/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 636, in _execute
    result = self._handler.run(task_vars=vars_copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arterome/.ansible/collections/ansible_collections/cisco/ise/plugins/action/support_bundle_download.py", line 91, in run
    data=download_response.data.decode(encoding='utf-8'),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
fatal: [localhost]: FAILED! => 
  msg: 'Unexpected failure during module execution: ''utf-8'' codec can''t decode byte 0x85 in position 0: invalid start byte'
  stdout: ''

PLAY RECAP *******************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Environment (please complete the following information):**
* ISE version and patch:  ISE version 3.2 patch None
* Ansible version:  ansible [core 2.17.3]
* ISE collection version:  cisco.ise  2.9.3       
* OS version:  macOS Sonoma Version 14.5

**Additional context**

**Comment by bvargasre** [comment]
I'm closing this issue due to inactivity
If the problem persists feel free to reopen the issue

**Comment by Jyothivaijnath** [comment]
> **Prerequisites**
> 
> * [x]  Have you tested the operation in the API directly?[x]  Do you have the latest ISE Collection version?[x]  Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.
> 
> **Name of the module** `cisco.ise.support_bundle_download`
> 
> **Describe the bug** After downloading the support bundle, the module fails with the following error:
> 
> **Expected behavior** After downloading the support bundle, task should not fail.
> 
> **Screenshots** Please provide an screenshot of the successful API call with cuRL, Postman, etc.
> 
> ![image](https://github.com/user-attachments/assets/f4c334c3-8496-4fb9-8c5a-c3abcfbd9722)
> 
> **Debug** Enable debugging and add CiscoISE output request and reponse.
> 
> * exporting `export ISE_DEBUG=True`
> * playbook `ise_debug: True`
> 
> ```
> TASK [Download support bundle] ***********************************************************************************************************************************************************************************
> task path: /Users/arterome/Documents/github/ise-cube/download_support_bundle.yml:6
> Attempt 1
> 
> Request
>         URL: https://ise.domain.com/ers/config/supportbundledownload
>         Method: PUT
>         Headers: 
>                 User-Agent: python-cisco-ise/3.3_patch_1
>                 Accept-Encoding: gzip, deflate
>                 Accept: application/json
>                 Connection: keep-alive
>                 authorization: Basic XXXXXXX
>                 Content-type: application/json;charset=utf-8
>         Params:
>               {}
>         Body:
>             {
>                 "ErsSupportBundleDownload": {
>                     "fileName": "ise-support-bundle-pk-ise-admin-08-08-2024-23-05.tar.gpg"
>                 }
>             }
>         Stream:
>                 True
> 
> Response
>         Status: 200 - 
>         Headers: 
>                 Content-Type: application/octet-stream
>                 Transfer-Encoding: chunked
>                 Connection: keep-alive
>                 Cache-Control: no-cache, no-store, must-revalidate
>                 Set-Cookie: JSESSIONIDSSO=81F52FF532D1B725E9272021C5E84419; Path=/; Secure; HttpOnly, APPSESSIONID=426416DFC59729AB5651583DF4E18C43; Path=/ers; Secure; HttpOnly
>                 Pragma: no-cache
>                 Expires: Thu, 01 Jan 1970 00:00:00 GMT
>                 X-Frame-Options: SAMEORIGIN
>                 Strict-Transport-Security: max-age=31536000; includeSubDomains
>                 X-Content-Type-Options: nosniff
>                 X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
>                 X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
>                 Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
>                 X-XSS-Protection: 1; mode=block
>                 Content-Disposition: attachment; filename="supportbundledownload.tar.gpg"
>                 Date: Wed, 14 Aug 2024 14:09:08 GMT
>                 Server: 
> Downloading ./ise-support-bundle-pk-ise-admin-08-08-2024-23-05.tar.gpg
> Downloaded ./ise-support-bundle-pk-ise-admin-08-08-2024-23-05.tar.gpg
> The full traceback is:
> Traceback (most recent call last):
>   File "/Users/arterome/Documents/github/ise-cube/venv/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 164, in run
>     res = self._execute()
>           ^^^^^^^^^^^^^^^
>   File "/Users/arterome/Documents/github/ise-cube/venv/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 636, in _execute
>     result = self._handler.run(task_vars=vars_copy)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/arterome/.ansible/collections/ansible_collections/cisco/ise/plugins/action/support_bundle_download.py", line 91, in run
>     data=download_response.data.decode(encoding='utf-8'),
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
> fatal: [localhost]: FAILED! => 
>   msg: 'Unexpected failure during module execution: ''utf-8'' codec can''t decode byte 0x85 in position 0: invalid start byte'
>   stdout: ''
> 
> PLAY RECAP *******************************************************************************************************************************************************************************************************
> localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
> ```
> 
> **Environment (please complete the following information):**
> 
> * ISE version and patch:  ISE version 3.2 patch None
> * Ansible version:  ansible [core 2.17.3]
> * ISE collection version:  cisco.ise  2.9.3
> * OS version:  macOS Sonoma Version 14.5
> 
> **Additional context**

**Comment by Jyothivaijnath** [comment]
I do have the same issue. It’s failing to download the support bundle..need help. 

If you a script for download the support bundle please share. I’ll try and see the results.
