### ISSUE TITLE
Network_device fails to delete

### ISSUE THREAD

**Issue by markatdxb** [CiscoISE/ansible-ise#148]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [ x] Do you have the latest ISE Collection version?
* [ x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Name of the module**
network_device

**Describe the bug**
starting collection 2.9.3 it fails to delete the device, coming with error 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution: 'NoneType' object is not iterable", "stdout": ""}

**Expected behavior**
Delete device from ISE

**Screenshots**
```
- name: Delete device from ISE
      cisco.ise.network_device:
        ise_hostname: "{{ ise_server }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: false
        state: absent
        id: "{{ item_ise_node }}"
      loop: "{{ net_device_id }}"
      loop_control:
        loop_var: item_ise_node


```**Debug**
Enable debugging and add CiscoISE output request and reponse.
* exporting `export ISE_DEBUG=True`
* playbook `ise_debug: True`

**Environment (please complete the following information):**
* ISE version and patch: 
* Ansible version: 9.10.0
* ISE collection version: 2.9.3 and higher
* OS version: 

**Additional context**
Add any other context about the problem here.

**Comment by fmunozmiranda** [comment]
Hi @markatdxb please share us debug of provider.

**Comment by markatdxb** [comment]
Hi, i just added debug
```
- name: Delete device from ISE
      cisco.ise.network_device:
        ise_hostname: "{{ ise_server }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: false
        state: absent
        ise_debug: true
        id: "{{ item_ise_node }}"
      loop: "{{ net_device_id }}"
      loop_control:
        loop_var: **item_ise_node**
```

result is the same
```
The full traceback is:
Traceback (most recent call last):
  File "/home/marek/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 120, in run
    item_results = self._run_loop(items)
  File "/home/marek/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 335, in _run_loop
    res = self._execute(variables=task_vars)
  File "/home/marek/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 644, in _execute
    result = self._handler.run(task_vars=vars_copy)
  File "/home/marek/.ansible/collections/ansible_collections/cisco/ise/plugins/action/network_device.py", line 253, in run
    obj = NetworkDevice(self._task.args, ise)
  File "/home/marek/.ansible/collections/ansible_collections/cisco/ise/plugins/action/network_device.py", line 63, in __init__
    for ip in network_device_iplist:
TypeError: 'NoneType' object is not iterable
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution: 'NoneType' object is not iterable",
    "stdout": ""
}
```

BTW: In documentation of this module is completely missing the option State:

**Comment by 1homas** [comment]
I have this same problem.
ansible_python_version: 3.12.7
ciscoisesdk         2.2.3
cisco.ise                                2.9.3

```
    - name: Remove Devices from ISE | {{ network_info.name }}
      when:
        - devices is defined
        - devices.meraki_response is defined
        - devices.meraki_response | length > 0
      loop: "{{ devices.meraki_response }}"
      cisco.ise.network_device:
        ise_hostname: "{{ ise_ppan_ip }}"
        ise_username: "{{ ise_username | default(omit) }}"
        ise_password: "{{ ise_password | default(omit) }}"
        state: absent
        name: "{{ item.name }}"
      register: devices_deleted
```

Downgrading to `cisco.ise` v2.9.2 fixes it.

**Comment by susanhooks** [comment]
I had this same problem, referenced in  #143. The workaround is to set an empty list for  NetworkDeviceIPList. 
```
NetworkDeviceIPLIst: []
```

**Comment by bvargasre** [comment]
Hi @markatdxb,  the new version 2.9.6 is available, try this new version and tell me how it goes.

**Comment by markatdxb** [comment]
@bvargasre  tested and looks OK. thanks
