### ISSUE TITLE
ciscoisesdk.exceptions.VersionError: Unknown API version, known versions are 3.1.0 and 3.1.1

### ISSUE THREAD

**Issue by kvaleriy** [CiscoISE/ansible-ise#42]
**Prerequisites**
* [X] Have you tested the operation in the API directly? ISE returns version 3.1.0.518;
* [X] Do you have the latest ISE Collection version? Yes, 2.5.0.

**Describe the bug**
Ansible returns next error: `ciscoisesdk.exceptions.VersionError: Unknown API version, known versions are 3.1.0 and 3.1.1`.

**Expected behavior**
Expect to provision ISE with ansible.

**Screenshots**
Cisco ISE returns next version of ISE.
![image](https://user-images.githubusercontent.com/63904570/173435558-96b266dc-b521-477d-93d1-3b8da162140b.png)

**Environment (please complete the following information):**
* ISE version and patch: 3.1.0.518
* Ansible version: 2.10.7
* ISE collection version: 2.5.0
* OS version: Linux version 4.4.0-92-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017

**Additional context**
Tried to set-up version 3.0.0, 3.1.0 and 3.1.0.518, but doesn't work.
```
(ansible_venv) user@las4779:~/repos/network_ansible$ ansible-playbook -i inventories/production/hosts --limit las1-ise playbooks/ciscoise-start.yml -vvvv
ansible-playbook 2.10.7
  config file = /home/user/repos/network_ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.6/site-packages/napalm_ansible/modules', '/usr/local/lib/python2.7/dist-packages/napalm_ansible', '/usr/lib/python2.7/site-packages/napalm_ansible', '/usr/local/lib/python2.7/site-packages/napalm_ansible', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm_ansible', '/home/user/repos/network_ansible/library/uswitchnn/modules', '/home/user/.virtualenvs/network_ansible/local/lib/python2.7/site-packages/napalm_ansible/modules', '/home/user/.virtualenvs/network_ansible/local/lib/python3.8/site-packages/napalm_ansible/modules', '/usr/local/lib/python3.8/site-packages/napalm_ansible/modules', '/home/user/miniconda3/envs/network_ansible_py3/lib/python3.8/site-packages/napalm_ansible']
  ansible python module location = /home/user/ansible_venv/lib/python3.8/site-packages/ansible
  executable location = /home/user/ansible_venv/bin/ansible-playbook
  python version = 3.8.6 (default, Dec  3 2020, 16:25:15) [GCC 5.4.0 20160609]
Using /home/user/repos/network_ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/user/repos/network_ansible/inventories/production/hosts as it did not pass its verify_file() method
script declined parsing /home/user/repos/network_ansible/inventories/production/hosts as it did not pass its verify_file() method
auto declined parsing /home/user/repos/network_ansible/inventories/production/hosts as it did not pass its verify_file() method
Parsed /home/user/repos/network_ansible/inventories/production/hosts inventory source with ini plugin
Loading collection cisco.ise from /home/user/.ansible/collections/ansible_collections/cisco/ise
Loading callback plugin default of type stdout, v2.0 from /home/user/ansible_venv/lib/python3.8/site-packages/ansible/plugins/callback/default.py
redirecting (type: callback) ansible.builtin.profile_tasks to ansible.posix.profile_tasks
Loading collection ansible.posix from /home/user/ansible_venv/lib/python3.8/site-packages/ansible_collections/ansible/posix
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Loading callback plugin ansible.posix.profile_tasks of type aggregate, v2.0 from /home/user/ansible_venv/lib/python3.8/site-packages/ansible_collections/ansible/posix/plugins/callback/profile_tasks.py

PLAYBOOK: ciscoise-start.yml **************************************************************************************************************************************************
Positional arguments: playbooks/ciscoise-start.yml
verbosity: 4
connection: smart
timeout: 30
become_method: sudo
tags: ('all',)
inventory: ('/home/user/repos/network_ansible/inventories/production/hosts',)
subset: las1-ise
forks: 5
1 plays in playbooks/ciscoise-start.yml

PLAY [Deply Cisco ISE] ********************************************************************************************************************************************************
Trying secret FileVaultSecret(filename='/home/user/repos/network_ansible/.vaultpasswd') for vault_id=default
Trying secret FileVaultSecret(filename='/home/user/repos/network_ansible/.vaultpasswd') for vault_id=default
Trying secret FileVaultSecret(filename='/home/user/repos/network_ansible/.vaultpasswd') for vault_id=default
META: ran handlers
Loading collection ansible.utils from /home/user/.ansible/collections/ansible_collections/ansible/utils

TASK [Import Server Certificate] **********************************************************************************************************************************************
task path: /home/user/repos/network_ansible/playbooks/ciscoise-start.yml:8
Monday 13 June 2022  19:59:37 +0000 (0:00:01.890)       0:00:01.890 *********** 
File lookup using /home/user/repos/network_ansible/roles/ciscoise/files/las.company.net_2022_key.pem as file
File lookup using /home/user/repos/network_ansible/roles/ciscoise/files/las.company.net_2022_key.pem as file
The full traceback is:
Traceback (most recent call last):
  File "/home/user/ansible_venv/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/home/user/ansible_venv/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 663, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/user/.ansible/collections/ansible_collections/cisco/ise/plugins/action/system_certificate_import.py", line 118, in run
    ise = ISESDK(params=self._task.args)
  File "/home/user/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 143, in __init__
    self.api = api.IdentityServicesEngineAPI(
  File "/home/user/ansible_venv/lib/python3.8/site-packages/ciscoisesdk-2.0.2-py3.8.egg/ciscoisesdk/api/__init__.py", line 979, in __init__
    raise VersionError(
ciscoisesdk.exceptions.VersionError: Unknown API version, known versions are 3.1.0 and 3.1.1.
fatal: [las1-ise]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

PLAY RECAP ********************************************************************************************************************************************************************
las1-ise                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Monday 13 June 2022  19:59:37 +0000 (0:00:00.087)       0:00:01.978 *********** 
=============================================================================== 
Import Server Certificate ---------------------------------------------------------------------------------------------------------------------------------------------- 0.09s
/home/user/repos/network_ansible/playbooks/ciscoise-start.yml:8 ----------------------------------------------------------------------------------------------------------
(ansible_venv) user@las4779:~/repos/network_ansible$ more playbooks/ciscoise-start.yml
- name: Deply Cisco ISE
  hosts: ciscoise
  vars:
    certificate_file: "{{ lookup('file', playbook_dir + '/' + '../roles/ciscoise/files/las.company.net_2022_key.pem') }}"
    private_key_file: "{{ lookup('file', playbook_dir + '/' + '../roles/ciscoise/files/las.company.net_2022_key.pem') }}"
  gather_facts: no
  tasks:
    - name: Import Server Certificate
      cisco.ise.system_certificate_import:
        ise_hostname: "{{ise_hostname}}"
        ise_username: "{{ise_username}}"
        ise_password: "{{ise_password}}"
        ise_verify: "{{ise_verify}}"
        admin: true
        allowExtendedValidity: true
        allowOutOfDateCert: true
        allowPortalTagTransferForSameSubject: true
        allowReplacementOfCertificates: true
        allowReplacementOfPortalGroupTag: true
        allowRoleTransferForSameSubject: true
        allowSHA1Certificates: true
        allowWildCardCertificates: true
        data: "{{ certificate_file }}"
        eap: true
        ims: true
        name: string
        password: "{{ certificate_passphrase }}"
        portal: true
        portalGroupTag: string
        privateKeyData: "{{ private_key_file }}"
        pxgrid: true
        radius: true
        saml: true
        validateCertificateExtensions: true

    - name: Create repository for upgrades
      cisco.ise.repository:
        ise_hostname: "{{ise_hostname}}"
        ise_username: "{{ise_username}}"
        ise_password: "{{ise_password}}"
        ise_verify: "{{ise_verify}}"
        state: present
        name: nefiles.las.company.net
        path: /files
        protocol: http
        serverName: nefiles.las.company.net

    - name: Update proxy server
      cisco.ise.proxy_connection_settings:
        ise_hostname: "{{ise_hostname}}"
        ise_username: "{{ise_username}}"
        ise_password: "{{ise_password}}"
        ise_verify: "{{ise_verify}}"
        state: present
        bypassHosts: "*.las.company.net"
        fqdn: proxy.las.company.net
        passwordRequired: false
        port: 3128
(ansible_venv) user@las4779:~/repos/network_ansible$ 
```

**Comment by fmunozmiranda** [comment]
Hi @kvaleriy , I think that it's a problem with ciscoisesdk version, please verify that you're using `2.0.4` (latest) or  if you want to try it with your actual version you may include the `ise_version` variable, like this: 
```yml
    - name: Create repository for upgrades
      cisco.ise.repository:
        ise_hostname: "{{ise_hostname}}"
        ise_username: "{{ise_username}}"
        ise_password: "{{ise_password}}"
        ise_verify: "{{ise_verify}}"
        ise_version: "{{ise_version}}"
        state: present
        name: nefiles.las.company.net
        path: /files
        protocol: http
        serverName: nefiles.las.company.net
```

Try it, and let know us if is working for you.

---
**Note:**

For your current ciscoisesdk version, the supported ISE API versions are: [3.1.0, 3.1.1].

3.1.1 is equivalent to ISE 3.1.0.518 API version.

---

**Comment by kvaleriy** [comment]
Thanks, it works if I define ISE version within role, but it means that module can't read group_vars correctly and I think it is bug. Tried to procced on test and found next error:
```(ansible_venv) user@las4779:~/repos/network_ansible$ ansible-playbook -i inventories/production/hosts --limit las1-ise playbooks/ciscoise-start.yml -vvvv
ansible-playbook 2.10.7
  config file = /home/user/repos/network_ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.6/site-packages/napalm_ansible/modules', '/usr/local/lib/python2.7/dist-packages/napalm_ansible', '/usr/lib/python2.7/site-packages/napalm_ansible', '/usr/local/lib/python2.7/site-packages/napalm_ansible', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm_ansible', '/home/user/repos/network_ansible/library/uswitchnn/modules', '/home/user/.virtualenvs/network_ansible/local/lib/python2.7/site-packages/napalm_ansible/modules', '/home/user/.virtualenvs/network_ansible/local/lib/python3.8/site-packages/napalm_ansible/modules', '/usr/local/lib/python3.8/site-packages/napalm_ansible/modules', '/home/user/miniconda3/envs/network_ansible_py3/lib/python3.8/site-packages/napalm_ansible']
  ansible python module location = /home/user/ansible_venv/lib/python3.8/site-packages/ansible
  executable location = /home/user/ansible_venv/bin/ansible-playbook
  python version = 3.8.6 (default, Dec  3 2020, 16:25:15) [GCC 5.4.0 20160609]
Using /home/user/repos/network_ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/user/repos/network_ansible/inventories/production/hosts as it did not pass its verify_file() method
script declined parsing /home/user/repos/network_ansible/inventories/production/hosts as it did not pass its verify_file() method
auto declined parsing /home/user/repos/network_ansible/inventories/production/hosts as it did not pass its verify_file() method
Parsed /home/user/repos/network_ansible/inventories/production/hosts inventory source with ini plugin
Loading collection cisco.ise from /home/user/.ansible/collections/ansible_collections/cisco/ise
Loading callback plugin default of type stdout, v2.0 from /home/user/ansible_venv/lib/python3.8/site-packages/ansible/plugins/callback/default.py
redirecting (type: callback) ansible.builtin.profile_tasks to ansible.posix.profile_tasks
Loading collection ansible.posix from /home/user/ansible_venv/lib/python3.8/site-packages/ansible_collections/ansible/posix
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Loading callback plugin ansible.posix.profile_tasks of type aggregate, v2.0 from /home/user/ansible_venv/lib/python3.8/site-packages/ansible_collections/ansible/posix/plugins/callback/profile_tasks.py

PLAYBOOK: ciscoise-start.yml ******************************************************************************************************************************************************************************
Positional arguments: playbooks/ciscoise-start.yml
verbosity: 4
connection: smart
timeout: 30
become_method: sudo
tags: ('all',)
inventory: ('/home/user/repos/network_ansible/inventories/production/hosts',)
subset: las1-ise
forks: 5
1 plays in playbooks/ciscoise-start.yml

PLAY [Deply Cisco ISE] ************************************************************************************************************************************************************************************
Trying secret FileVaultSecret(filename='/home/user/repos/network_ansible/.vaultpasswd') for vault_id=default
Trying secret FileVaultSecret(filename='/home/user/repos/network_ansible/.vaultpasswd') for vault_id=default
Trying secret FileVaultSecret(filename='/home/user/repos/network_ansible/.vaultpasswd') for vault_id=default
META: ran handlers
Loading collection ansible.utils from /home/user/.ansible/collections/ansible_collections/ansible/utils

TASK [Import Server Certificate] **************************************************************************************************************************************************************************
task path: /home/user/repos/network_ansible/playbooks/ciscoise-start.yml:8
Thursday 16 June 2022  19:43:19 +0000 (0:00:02.294)       0:00:02.294 ********* 
File lookup using /home/user/repos/network_ansible/roles/ciscoise/files/las.company.net_2022.crt as file
File lookup using /home/user/repos/network_ansible/roles/ciscoise/files/las.company.net_2022.key as file
fatal: [las1-ise]: FAILED! => {
    "changed": false,
    "msg": "An error occured when executing operation. The error was: [400] - Import failed as SAML certificate cannot be used with any other role\n{\n  \"response\" : {\n    \"status\" : \"Fail\",\n    \"message\" : \"Import failed as SAML certificate cannot be used with any other role\",\n    \"id\" : null\n  },\n  \"version\" : \"1.0.0\"\n}"
}

PLAY RECAP ************************************************************************************************************************************************************************************************
las1-ise                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Thursday 16 June 2022  19:43:20 +0000 (0:00:01.154)       0:00:03.448 ********* 
=============================================================================== 
Import Server Certificate -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.15s
/home/user/repos/network_ansible/playbooks/ciscoise-start.yml:8 --------------------------------------------------------------------------------------------------------------------------------------
(ansible_venv) user@las4779:~/repos/network_ansible$ more playbooks/ciscoise-start.yml 
- name: Deply Cisco ISE
  hosts: ciscoise
  vars:
    certificate_file: "{{ lookup('file', playbook_dir + '/' + '../roles/ciscoise/files/las.company.net_2022.crt') }}"
    private_key_file: "{{ lookup('file', playbook_dir + '/' + '../roles/ciscoise/files/las.company.net_2022.key') }}"
  gather_facts: no
  tasks:
    - name: Import Server Certificate
      cisco.ise.system_certificate_import:
        ise_hostname: "{{ise_hostname}}"
        ise_username: "{{ise_username}}"
        ise_password: "{{ise_password}}"
        ise_verify: "{{ise_verify}}"
        ise_version: "{{ise_version}}"
        admin: true
        allowExtendedValidity: true
        allowOutOfDateCert: true
        allowPortalTagTransferForSameSubject: true
        allowReplacementOfCertificates: true
        allowReplacementOfPortalGroupTag: true
        allowRoleTransferForSameSubject: true
        allowSHA1Certificates: true
        allowWildCardCertificates: true
        data: "{{ certificate_file }}"
        eap: true
        ims: true
        name: string
        password: "{{ certificate_passphrase }}"
        portal: true
        portalGroupTag: string
        privateKeyData: "{{ private_key_file }}"
        pxgrid: true
        radius: true
        saml: true
        validateCertificateExtensions: true
(ansible_venv) user@las4779:~/repos/network_ansible$ ```
Role is olone inside playbook, what would be the issue?

**Comment by jbogarin** [comment]
@kvaleriy to understand a bit more, within your host file or as part of the group_vars file you are defining the `ise_version` variable, but when you are running the playbook, it's not using it to connect to ISE?

**Comment by fmunozmiranda** [comment]
Hey @kvaleriy , the reason for the error you're getting is due to using the latest ansible collection with an SDK version that isn't recommended, so that's why you're getting that version error. On the other hand, even if the "ise_version" variable is defined in group_vars, it has to be specified in the request header.
You can handle these variables more comfortably using YAML Anchoring, something like this:
```yml
  vars:
     ise_login: &ise_login
       ise_hostname: "{{ise_hostname}}"
       ise_username: "{{ise_username}}"
       ise_password: "{{ise_password}}"
       ise_verify: "{{ise_verify}}"
       ise_version: "{{ise_version}}"

   tasks:
   - name: Create
     cisco.ise.identity_group:
       <<: *ise_login
       state: present
       name: "Salts"
       description: "Sales"
       parent: "NAC Group:NAC:IdentityGroups:User Identity Groups"
     register:identity_group

**Comment by kvaleriy** [comment]
@fmunozmiranda I have tried to use previous version of Cisco ISE collection 2.4.1 and use the same approach as you defined in snippet, but still have the same:
```(ansible_venv) vkayukov@las4779:~/repos/network_ansible$ ansible-galaxy collection list | grep cisco.ise
cisco.ise     2.4.1  
(ansible_venv) vkayukov@las4779:~/repos/network_ansible$ more playbooks/ciscoise-deployment.yml
- name: Deply Cisco ISE
  hosts: ciscoise
  vars:
    certificate_file: "{{ lookup('file', playbook_dir + '/' + '../roles/ciscoise/files/las.demonware.net_2022.crt') }}"
    private_key_file: "{{ lookup('file', playbook_dir + '/' + '../roles/ciscoise/files/las.demonware.net_2022.key') }}"
    ise_login: &ise_login
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      ise_version: "{{ise_version}}"
  gather_facts: no
  tasks:
  - name: Import Server Certificate
    cisco.ise.system_certificate_import:
      <<: *ise_login
      admin: true
      allowExtendedValidity: true
      allowOutOfDateCert: true
      allowPortalTagTransferForSameSubject: true
      allowReplacementOfCertificates: true
      allowReplacementOfPortalGroupTag: true
      allowRoleTransferForSameSubject: true
      allowSHA1Certificates: true
      allowWildCardCertificates: true
      data: "{{ certificate_file }}"
      eap: true
      ims: true
      name: string
      password: "{{ certificate_passphrase }}"
      portal: true
      portalGroupTag: string
      privateKeyData: "{{ private_key_file }}"
      pxgrid: true
      radius: true
      saml: true
      validateCertificateExtensions: true
(ansible_venv) vkayukov@las4779:~/repos/network_ansible$ ansible-playbook playbooks/ciscoise-deployment.yml -vvv
ansible-playbook 2.10.7
  config file = /home/vkayukov/repos/network_ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.6/site-packages/napalm_ansible/modules', '/usr/local/lib/python2.7/dist-packages/napalm_ansible', '/usr/lib/python2.7/site-packages/napalm_ansible', '/usr/local/lib/python2.7/site-packages/napalm_ansible', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm_ansible', '/home/vkayukov/repos/network_ansible/library/uswitchnn/modules', '/home/vkayukov/.virtualenvs/network_ansible/local/lib/python2.7/site-packages/napalm_ansible/modules', '/home/vkayukov/.virtualenvs/network_ansible/local/lib/python3.8/site-packages/napalm_ansible/modules', '/usr/local/lib/python3.8/site-packages/napalm_ansible/modules', '/home/vkayukov/miniconda3/envs/network_ansible_py3/lib/python3.8/site-packages/napalm_ansible']
  ansible python module location = /home/vkayukov/ansible_venv/lib/python3.8/site-packages/ansible
  executable location = /home/vkayukov/ansible_venv/bin/ansible-playbook
  python version = 3.8.6 (default, Dec  3 2020, 16:25:15) [GCC 5.4.0 20160609]
Using /home/vkayukov/repos/network_ansible/ansible.cfg as config file
host_list declined parsing /home/vkayukov/repos/network_ansible/inventories/production/hosts as it did not pass its verify_file() method
script declined parsing /home/vkayukov/repos/network_ansible/inventories/production/hosts as it did not pass its verify_file() method
auto declined parsing /home/vkayukov/repos/network_ansible/inventories/production/hosts as it did not pass its verify_file() method
Parsed /home/vkayukov/repos/network_ansible/inventories/production/hosts inventory source with ini plugin
redirecting (type: callback) ansible.builtin.profile_tasks to ansible.posix.profile_tasks
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: ciscoise-deployment.yml ************************************************************************************************************************************************************************
1 plays in playbooks/ciscoise-deployment.yml

PLAY [Deply Cisco ISE] ***********************************************************************************************************************************************************************************
META: ran handlers

TASK [Import Server Certificate] *************************************************************************************************************************************************************************
task path: /home/vkayukov/repos/network_ansible/playbooks/ciscoise-deployment.yml:14
Tuesday 21 June 2022  23:14:18 +0000 (0:00:02.188)       0:00:02.188 ********** 
fatal: [las1-ise.las.demonware.net]: FAILED! => {
    "changed": false,
    "msg": "An error occured when executing operation. The error was: [400] - Import failed as SAML certificate cannot be used with any other role\n{\n  \"response\" : {\n    \"status\" : \"Fail\",\n    \"message\" : \"Import failed as SAML certificate cannot be used with any other role\",\n    \"id\" : null\n  },\n  \"version\" : \"1.0.0\"\n}"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************
las1-ise.las.demonware.net : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Tuesday 21 June 2022  23:14:19 +0000 (0:00:01.014)       0:00:03.202 ********** 
=============================================================================== 
Import Server Certificate ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.01s
/home/vkayukov/repos/network_ansible/playbooks/ciscoise-deployment.yml:14 -------------------------------------------------------------------------------------------------------------------------------
(ansible_venv) vkayukov@las4779:~/repos/network_ansible$ ```

**Comment by fmunozmiranda** [comment]
Hey @kvaleriy, apparently the issue initially detected was resolved, therefore it will be closed, a new one was opened to deal with more emphasis on this last problem you had, it is issue https://github.com/CiscoISE/ansible-ise/issues/43.
