### ISSUE TITLE
node_group_node_info consistently produces fatal error

### ISSUE THREAD

**Issue by bootsmo** [CiscoISE/ansible-ise#77]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest ISE Collection version?

**Describe the bug**
Any execution of cisco.ise.node_group_node_info produces a fatal error.  This has been tested for node groups with members and node groups without members.

**Expected behavior**
Node groups without members should return an empty list.
Node groups with members should return a list of members' hostnames.

**Screenshots**
Response via Postman for node group with no members:
```
{
  "response" : [ ],
  "version" : "1.0.0"
}
```

Response via Postman for node group with single member:
```
{
  "response" : [ {
    "hostname" : "<redacted>"
  } ],
  "version" : "1.0.0"
}
```

Ansible call to reproduce:
```
      - name: Get population of each group.
        cisco.ise.node_group_node_info:
          <<: *ise_login
          nodeGroupName: "NodeGroup2"
```

Ansible module error:
```
task path: /opt/app/ansible/nodeupdate/node-groups-populate.yml:45
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 681, in _execute
    result["_ansible_no_log"] = self._play_context.no_log
TypeError: 'NoneType' object does not support item assignment
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Environment (please complete the following information):**
* ISE version and patch:  3.1 patch 1
* Ansible version:  2.10.8
* ISE collection version: 2.5.10
* OS version: Ubuntu jammy

**Additional context**

**Comment by bvargasre** [comment]
Hi @bootsmo could you activate the debug pass me the output when it fails

**Comment by bootsmo** [comment]
I changed ise_debug to true and reran.  Full console output below:
```
root@3f752bb4e544:/opt/app/ansible# ansible-playbook -vvv node-group-test.yml
ansible-playbook 2.10.8
  config file = /opt/app/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Using /opt/app/ansible/ansible.cfg as config file
host_list declined parsing /opt/app/ansible/hosts as it did not pass its verify_file() method
script declined parsing /opt/app/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /opt/app/ansible/hosts as it did not pass its verify_file() method
Parsed /opt/app/ansible/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: node-group-test.yml ******************************************************************************************
1 plays in node-group-test.yml
Read vars_file 'vars/common/vars.yml'
Read vars_file 'vars/common/vars.yml'
Read vars_file 'vars/common/vars.yml'

PLAY [Populate PSN node groups.] ***************************************************************************************
Read vars_file 'vars/common/vars.yml'
META: ran handlers
Read vars_file 'vars/common/vars.yml'

TASK [Get population of each group.] ***********************************************************************************
task path: /opt/app/ansible/node-group-test.yml:22
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 681, in _execute
    result["_ansible_no_log"] = self._play_context.no_log
TypeError: 'NoneType' object does not support item assignment
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

root@3f752bb4e544:/opt/app/ansible# 
```

**Comment by bvargasre** [comment]
Hi @bootsmo, ansible-ise v2.5.11 is up
Try with this new version and let me know if works for you

**Comment by bootsmo** [comment]
Confirmed:  module now returns data as expected without issue.
